---

-
  name: Set proxy vars
  set_fact:
    proxy_state: "off"
  when: proxy_host is undefined or proxy_host == ""

-
  name: Set node proxy configuration without authentication
  shell: "networksetup -set{{ item }} {{ proxy_device }} {{ proxy_host }} {{ proxy_port }} off"
  with_items: "{{ proxy_ctx }}"
  become: true
  when:
    - proxy_host is defined and proxy_host != ''

- pause:
    prompt: |
      Currently mac machines require that authenticated proxies to be manually configured.

      You can either ssh into the machine and manually run the "networksetup" command (requires root user) or remotely connect to it.

      Sample command:

      networksetup -setwebproxy {{ proxy_device }} {{ proxy_host }} {{ proxy_port }} on {{ proxy_user }} {{ proxy_pass }}

      Hit enter to continue or ctrl + c to cancel
    when:
      - proxy_host is defined and proxy_host != ''
      - proxy_user is defined and proxy_user != ''
      - proxy_pass is defined and proxy_pass != ''

-
  name: Sets proxy status
  shell: "networksetup -set{{ item }}state {{ proxy_device }} {{ proxy_state | default('on') }}"
  with_items: "{{ proxy_ctx }}"
  become: true
